#!/usr/bin/env python3
import sys
import math

def factory(num):
    """Gets the factors of a number and prints them"""
    if num % 2 == 0:
        i = 2
        print("{}={}*{}".format(num, num // i, i))
        return
    
    sq = int(math.sqrt(num)) + 1
    for i in range(3, sq + 1, 2):
        if num % i == 0:
            print("{}={}*{}".format(num, num // i, i))
            return

    # If no factors found, it means num is a prime, hence it can be represented as num*1
    print("{}={}*{}".format(num, num, 1))

def factors(filename):
    """Reads the file and prints the factors of each number"""
    with open(filename, encoding="utf-8") as my_file:
        for line in my_file:
            n = int(line.strip())
            factory(n)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    
    factors(sys.argv[1])
